#include <iostream>
#include "Dictionary.cpp"
using namespace std;
int main()
{
    Dictionary<int, string> test1;
    test1.insertElement(1, "John");
    test1.insertElement(2, "Blake");
    test1.insertElement(3, "Rose");
    test1.insertElement(4, "Angela");
    test1.insertElement(5, "Francesca");
    test1.graph(cout);
    test1.printInOrder();
    cout << "--copying--" << endl;
    Dictionary<int, string> test2(test1);
    test2.graph(cout);
    test2.printInOrder();
    cout << "--clearing and assigning--" << endl;
    test1.clearContents();
    test1 = test2;
    test1.graph(cout);
    cout << "--searching--" << endl;
    string infoToFind = "NULL";
    test1.search(5, infoToFind);
    cout << "found: " << infoToFind << endl;
    cout << "--removing--" << endl;
    test2.insertElement(6, "Pablo");
    test2.insertElement(7, "March");
    test2.insertElement(8, "Vanessa");
    test2.insertElement(9, "Steven");
    test2.insertElement(10, "Chad");
    test2.insertElement(11, "Marcello");
    test2.insertElement(12, "Juan");
    test2.insertElement(13, "Joanne");
    test2.insertElement(14, "Frank");
    test2.graph(cout);
    test2.printInOrder();
    cout << "After removal" << endl;
    test2.remove(8);
    test2.graph(cout);
    test2.printInOrder();
    cout << "--readFromFile--" << endl;
    Dictionary<string, int> test3;
    readFromFile(test3, "File.txt");
    test3.printInOrder();
    cout << "--Mass adding--" << endl;
    Dictionary<int, string> test4;
    test4.insertElement(1, "A");
    test4.insertElement(2, "B");
    test4.insertElement(3, "C");
    test4.insertElement(4, "D");
    test4.insertElement(5, "E");
    test4.insertElement(6, "F");
    test4.insertElement(7, "G");
    test4.insertElement(8, "H");
    test4.insertElement(9, "I");
    test4.insertElement(10, "J");
    test4.insertElement(11, "K");
    test4.insertElement(12, "L");
    test4.insertElement(13, "M");
    test4.insertElement(14, "N");
    test4.insertElement(15, "O");
    test4.insertElement(16, "P");
    test4.insertElement(17, "Q");
    test4.insertElement(18, "R");
    test4.insertElement(19, "S");
    test4.insertElement(20, "T");
    test4.insertElement(21, "U");
    test4.insertElement(22, "V");
    test4.insertElement(23, "W");
    test4.insertElement(24, "X");
    test4.insertElement(25, "Y");
    test4.insertElement(26, "Z");
    test4.insertElement(27, "AA");
    test4.insertElement(28, "BB");
    test4.insertElement(29, "CC");
    test4.insertElement(30, "DD");
    test4.insertElement(31, "EE");
    test4.insertElement(32, "FF");
    test4.insertElement(33, "GG");
    test4.insertElement(34, "HH");
    test4.graph(cout);
   cout << "--Mass removing--" << endl;
    test4.remove(28);
    test4.remove(29);
    test4.remove(30);
    test4.remove(31);
    test4.remove(32);
    test4.remove(33);
    test4.remove(34);
    test4.remove(27);
    test4.remove(26);
    test4.remove(25);
    test4.remove(24);
    test4.remove(23);
    test4.remove(22);
    test4.remove(21);
    test4.remove(20);
    test4.remove(19);
    test4.graph(cout);
    cout << "--END--" << endl;
}